#!/bin/bash -e
#set -o xtrace
#if [ $# != 1 ]; then
#	echo "Usage: $0 <containername>"
#	exit 1
#fi
if [ `whoami` != "root" ]; then
    echo "This script must be run as root"
    exit 1
fi
if [ ! -d "/var/lib/lxc" ]; then
    echo "/var/lib/lxc not found, exiting..."
    exit 1
fi
LXCLS="$(lxc-ls | tr -s ' ' | sed 's/ *$//g')"
echo "$LXCLS" | tr ' ' '\n' |  while read item; do
    output=$(lxc-info $item)
    echo "$output"
    printf "\n"
done
